clear;clc;close all

% CODE RUNS ALL ENSEMBLE CODES IN SEQUENCE

% CODE AUTHORED BY: SHAWHIN TALEBI
% THE UNIVERSITY OF TEXAS AT DALLAS
% MULTI-INTEGRATED REMOTE SENSING AND SIMULATION (MINTS)

A930_LPD_ensemble_MT;
A930_RPD_ensemble_MT;
A930_APD_ensemble_MT;
A930_PDD_ensemble_MT;
A930_ILM_ensemble_MT;